#!/usr/bin/env bash

python_cmd='python'
BASEDIR=$(dirname $0)

VENVDIR=$BASEDIR/venv/

if [ ! -d "$VENVDIR" ]; then
    $python_cmd -m venv $VENVDIR 
    echo "New venv created on your filesystem at $VENVDIR."
    $VENVDIR/bin/python -m pip install -r $BASEDIR/requirements.txt
fi

venv_path=$VENVDIR/bin/

$venv_path$python_cmd -u $BASEDIR/edgepi-thermocouple.py $@
